# -*- coding: utf-8 -*-
{
    'name': "upopet",
    'summary': """Veterinario management""",
    'description': """Veterinario management: veterinarios, mascotas, citas...""",
    'author': "Equipo 15",
    'category': 'Clinica',
    'version': '0.2',
    'depends': ['base'],
    'data': ['views/mascota_view.xml',
            'views/tratamiento_view.xml',
            'views/cita_view.xml',
            'views/pruebamedica_view.xml',
            'views/clinica_view.xml',
            'views/persona_view.xml',
            'views/veterinario_view.xml',
            'views/medicamento_view.xml',
            'views/laboratorio_view.xml',
             ],
    #'demo': ['demo/upopet_demo.xml'],
    'application': True,
}